"""add faq and video frame jobs

Reuses the existing `job_status` and `provider_name` Postgres TYPEs (see
9a2f6c1d8e4b_add_breakdown_jobs.py) rather than declaring new enums — must reference
them with create_type=False, or `alembic upgrade` fails with "type ... already exists".

Revision ID: 0341c13705d6
Revises: 8b1d4e7a06c3
Create Date: 2026-09-14 13:25:24.377470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0341c13705d6'
down_revision: Union[str, None] = '8b1d4e7a06c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    job_status = postgresql.ENUM(
        'QUEUED', 'PARSING', 'EXTRACTING', 'STRUCTURING', 'SUCCEEDED', 'FAILED', 'CANCELLED',
        name='job_status', create_type=False,
    )
    provider_name = postgresql.ENUM('GEMINI', 'OPENAI', name='provider_name', create_type=False)

    op.create_table('faq_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', provider_name, nullable=False),
    sa.Column('status', job_status, nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_jobs_project_id'), 'faq_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_faq_jobs_status'), 'faq_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_faq_jobs_user_id'), 'faq_jobs', ['user_id'], unique=False)
    op.create_table('project_video_frames',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('video_media_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_media_id'], ['project_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_media_id', 'order_index', name='uq_video_frame_media_order')
    )
    op.create_index(op.f('ix_project_video_frames_project_id'), 'project_video_frames', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_video_frames_user_id'), 'project_video_frames', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_video_frames_video_media_id'), 'project_video_frames', ['video_media_id'], unique=False)
    op.create_table('video_frame_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('video_media_id', sa.UUID(), nullable=True),
    sa.Column('status', job_status, nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_media_id'], ['project_media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_frame_jobs_project_id'), 'video_frame_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_video_frame_jobs_status'), 'video_frame_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_video_frame_jobs_user_id'), 'video_frame_jobs', ['user_id'], unique=False)
    op.create_table('project_video_frame_blobs',
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['project_video_frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('frame_id')
    )
    # NOTE: autogenerate also proposed dropping saq_stats/saq_versions/saq_jobs (tables
    # SAQ itself manages at runtime, invisible to our SQLAlchemy models — dropping them
    # here would break the job queue) and altering chat_sessions/user_profiles indexes
    # (pre-existing drift unrelated to this change) — both removed by hand; this
    # migration only adds the four new tables above.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_video_frame_blobs')
    op.drop_index(op.f('ix_video_frame_jobs_user_id'), table_name='video_frame_jobs')
    op.drop_index(op.f('ix_video_frame_jobs_status'), table_name='video_frame_jobs')
    op.drop_index(op.f('ix_video_frame_jobs_project_id'), table_name='video_frame_jobs')
    op.drop_table('video_frame_jobs')
    op.drop_index(op.f('ix_project_video_frames_video_media_id'), table_name='project_video_frames')
    op.drop_index(op.f('ix_project_video_frames_user_id'), table_name='project_video_frames')
    op.drop_index(op.f('ix_project_video_frames_project_id'), table_name='project_video_frames')
    op.drop_table('project_video_frames')
    op.drop_index(op.f('ix_faq_jobs_user_id'), table_name='faq_jobs')
    op.drop_index(op.f('ix_faq_jobs_status'), table_name='faq_jobs')
    op.drop_index(op.f('ix_faq_jobs_project_id'), table_name='faq_jobs')
    op.drop_table('faq_jobs')
    # ### end Alembic commands ###
