"""add chat_sessions starred and context summary fields

Revision ID: 46f274f3644d
Revises: c7a2f4d8b915
Create Date: 2026-08-31 00:00:00.000001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '46f274f3644d'
down_revision: Union[str, None] = 'c7a2f4d8b915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Strictly increasing insertion-order marker for chat_service.py's replay/compaction
    # ordering — created_at can't serve this role since Postgres's now()/CURRENT_TIMESTAMP
    # is fixed for the whole transaction (every message persisted in one turn shares an
    # identical created_at), and the id column is a random UUID with no ordering relation
    # to insertion order. GENERATED BY DEFAULT AS IDENTITY backfills existing rows in
    # insertion order automatically (Postgres 10+).
    op.add_column(
        'chat_messages',
        sa.Column('sequence', sa.BigInteger(), sa.Identity(), nullable=False),
    )
    op.create_index('ix_chat_messages_sequence', 'chat_messages', ['sequence'], unique=True)

    op.add_column(
        'chat_sessions',
        sa.Column('starred', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('chat_sessions', sa.Column('context_summary', sa.Text(), nullable=True))
    op.add_column(
        'chat_sessions',
        sa.Column('summarized_through_message_id', postgresql.UUID(as_uuid=True), nullable=True),
    )
    # ON DELETE SET NULL — chat_messages rows cascade-delete when their session is
    # deleted, and one of those rows may be the very one this column points at; SET NULL
    # avoids any FK-violation risk from cascade/ordering rather than the default RESTRICT.
    op.create_foreign_key(
        'fk_chat_sessions_summarized_through_message_id',
        'chat_sessions',
        'chat_messages',
        ['summarized_through_message_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_index(
        'ix_chat_sessions_summarized_through_message_id',
        'chat_sessions',
        ['summarized_through_message_id'],
    )


def downgrade() -> None:
    op.drop_index('ix_chat_sessions_summarized_through_message_id', table_name='chat_sessions')
    op.drop_constraint(
        'fk_chat_sessions_summarized_through_message_id', 'chat_sessions', type_='foreignkey'
    )
    op.drop_column('chat_sessions', 'summarized_through_message_id')
    op.drop_column('chat_sessions', 'context_summary')
    op.drop_column('chat_sessions', 'starred')

    op.drop_index('ix_chat_messages_sequence', table_name='chat_messages')
    op.drop_column('chat_messages', 'sequence')
